# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 22:10
from __future__ import unicode_literals

import datetime
import random

from django.db import migrations
from django.utils import timezone


def forwards_func(apps, schema_editor):
    Poll = apps.get_model("polls", "Poll")
    Question = apps.get_model("polls", "Question")
    Choice = apps.get_model("polls", "Choice")

    today = timezone.now()

    questions = []
    polls = []
    choices = []

    # from now to 2 weeks in the past
    for days_ago in xrange(14):
        date = today - datetime.timedelta(days=days_ago)

        for i in xrange(1000):
            polls.append(Poll(
                name=u'Poll {}'.format(i),
                pub_date=date,
            ))

    Poll.objects.bulk_create(polls)

    # create questions
    for poll_id in Poll.objects.all().values_list('id', flat=True):
        for i in xrange(10):
            questions.append(Question(
                question_text=u'Question {}'.format(i),
                poll_id=poll_id
            ))

    Question.objects.bulk_create(questions)

    for question_id in Question.objects.all().values_list('id', flat=True):
        for i in xrange(10):
            choices.append(Choice(
                question_id=question_id,
                choice_text=u'choice {}'.format(i),
                votes=random.randint(0, 100)
            ))

    Choice.objects.bulk_create(choices)


def reverse_func(apps, schema_editor):
    Question = apps.get_model("polls", "Question")
    Choice = apps.get_model("polls", "Choice")

    Question.objects.all().delete()
    Choice.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
